### PR TITLE
quick syntax fix

### PR DESCRIPTION
**Pull request by ulkas**
https://github.com/loreii/HeaderTool/issues/7

### CODE REVIEW

**Comment by norstbox** [comment]
As noted in the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions#Differences_to_the_older_JS1.7JS1.8_comprehensions), comprehensions only work with `for...of` and not with `for...in` iterations. So a proper quick fix will be:
> var s = [for (i **of** hash) toHexString(hash.charCodeAt(i))].join("");

**Comment by ulkas** [comment]
thnks @norstbox , i edited it.

**Comment by davidshepherd7** [comment]
I couldn't get it to work even with your patches (on Firefox 47) does it work for you?

**Comment by norstbox** [comment]
@davidshepherd7 This patch works for me. Did you replace `headertoolModule.js` with [this one](https://raw.githubusercontent.com/ulkas/HeaderTool/08580a4abe4242b57915eb3eac63b3ccd2da5256/modules/headertoolModule.js)? Please be in mind that `xpinstall.signatures.required` must be set to `false` in `about:config`.

**Comment by davidshepherd7** [comment]
I pulled the branch used for this pull-request and built it using the `build.sh` script, or at least I think I did. If it works for you then I probably just screwed up the build process somewhere (I have no idea what I'm doing with building Firefox extensions). Yeah I set the signatures flag.

I'll have another go, thanks for the reply!

**Comment by loreii** [comment]
merged thanks for the support, i'm going to release it

**Pull request merged**
